// Mock inventory data — sourced from allusedautoparts.world real listings
export interface PartListing {
  id: string
  name: string
  make: string
  partType: string
  price: number
  mileageTier?: string
  condition: 'excellent' | 'good' | 'fair'
  warranty: string
  location: string
  image: string
  rating: number
  reviews: number
  description: string
  compatibility: string[]
  sku?: string
  vinMatch?: boolean
}

export const mockParts: PartListing[] = [
  // ── Real listings from allusedautoparts.world ──────────────────────────────
  {
    id: 'part-001',
    name: '8-Speed Automatic Transmission (opt M5U)',
    make: 'Chevrolet Silverado 1500',
    partType: 'Transmissions',
    price: 1015,
    mileageTier: '60k–90k miles',
    condition: 'excellent',
    warranty: '90 days',
    location: 'Detroit, MI',
    image: '/images/used-transmissions.jpg',
    rating: 4.8,
    reviews: 47,
    description: '2018 Chevrolet Truck-Silverado 1500 (1999 Up) AT, 4x2, 6.2L, 8 speed (opt M5U). VIN-verified, shift tested, fluid integrity checked.',
    compatibility: ['2018 Chevrolet Silverado 1500 4x2 6.2L'],
    sku: 'TRN-34771',
    vinMatch: true,
  },
  {
    id: 'part-002',
    name: 'Manual Transmission MT 4-Cylinder',
    make: 'Mazda 626',
    partType: 'Transmissions',
    price: 944,
    mileageTier: '75k–100k miles',
    condition: 'good',
    warranty: '90 days',
    location: 'Phoenix, AZ',
    image: '/images/used-transmissions.jpg',
    rating: 4.6,
    reviews: 31,
    description: '2000 Mazda 626 MT, 4 cylinder transmission. Smooth gear engagement, fully tested before shipment.',
    compatibility: ['1998-2002 Mazda 626 4-cyl'],
    sku: 'TRN-101025',
    vinMatch: true,
  },
  {
    id: 'part-003',
    name: 'Engine 5.7L VIN H AWD',
    make: 'Chrysler 300',
    partType: 'Engines',
    price: 2050,
    mileageTier: '80k–110k miles',
    condition: 'excellent',
    warranty: '90 days',
    location: 'Houston, TX',
    image: '/images/used-engines.jpg',
    rating: 4.9,
    reviews: 58,
    description: '2008 Chrysler 300 5.7L (VIN H, 8th digit), AWD engine. Compression tested, no leaks, clean history.',
    compatibility: ['2007-2010 Chrysler 300 5.7L AWD'],
    sku: 'ENG-127831',
    vinMatch: true,
  },
  {
    id: 'part-004',
    name: 'TH400 Automatic Transmission',
    make: 'Chevrolet Caprice',
    partType: 'Transmissions',
    price: 560,
    mileageTier: 'Unknown miles (rebuilt)',
    condition: 'good',
    warranty: '60 days',
    location: 'Chicago, IL',
    image: '/images/used-transmissions.jpg',
    rating: 4.5,
    reviews: 22,
    description: '1966 Chevrolet Caprice (1979 Down) AT, TH400. Classic heavy-duty automatic, rebuilt and road tested.',
    compatibility: ['1965-1979 Chevrolet Classic AT TH400'],
    sku: 'TRN-27478',
    vinMatch: false,
  },
  {
    id: 'part-005',
    name: 'Engine 3.5L V6 2GR-FE',
    make: 'Toyota Sienna',
    partType: 'Engines',
    price: 1650,
    mileageTier: '70k–95k miles',
    condition: 'excellent',
    warranty: '90 days',
    location: 'Los Angeles, CA',
    image: '/images/used-engines.jpg',
    rating: 4.8,
    reviews: 63,
    description: 'Low-mileage Toyota Sienna 3.3L V6 engine matched by VIN. Compression and leak tested, clean oil.',
    compatibility: ['2004-2010 Toyota Sienna 3.3L V6'],
    sku: 'ENG-88210',
    vinMatch: true,
  },
  {
    id: 'part-006',
    name: 'CVT Automatic Transmission',
    make: 'Nissan Altima',
    partType: 'Transmissions',
    price: 875,
    mileageTier: '65k–80k miles',
    condition: 'good',
    warranty: '90 days',
    location: 'Dallas, TX',
    image: '/images/used-transmissions.jpg',
    rating: 4.4,
    reviews: 39,
    description: 'Nissan Altima CVT transmission, 4-cylinder. Smooth belt, no slipping, fluid clean. VIN matched.',
    compatibility: ['2013-2018 Nissan Altima 2.5L CVT'],
    sku: 'TRN-55892',
    vinMatch: true,
  },
  {
    id: 'part-007',
    name: 'Engine 2.4L DOHC 4-Cylinder',
    make: 'Honda Accord',
    partType: 'Engines',
    price: 1195,
    mileageTier: '60k–85k miles',
    condition: 'excellent',
    warranty: '90 days',
    location: 'Miami, FL',
    image: '/images/used-engines.jpg',
    rating: 4.9,
    reviews: 77,
    description: 'Honda Accord 2.4L K24A engine, low mileage donor. VTEC tested, no oil burning, clean compression.',
    compatibility: ['2008-2012 Honda Accord 2.4L 4-cyl'],
    sku: 'ENG-72341',
    vinMatch: true,
  },
  {
    id: 'part-008',
    name: '6-Speed Automatic Transmission',
    make: 'Ford F-150',
    partType: 'Transmissions',
    price: 1120,
    mileageTier: '75k–100k miles',
    condition: 'excellent',
    warranty: '90 days',
    location: 'Atlanta, GA',
    image: '/images/used-transmissions.jpg',
    rating: 4.7,
    reviews: 54,
    description: 'Ford F-150 6R80 6-speed automatic. Shift tested, all gears engage properly, no slipping.',
    compatibility: ['2011-2017 Ford F-150 6R80 5.0L / 3.5L EcoBoost'],
    sku: 'TRN-66120',
    vinMatch: true,
  },
  {
    id: 'part-009',
    name: 'Engine 5.3L V8 LS',
    make: 'Chevrolet Tahoe',
    partType: 'Engines',
    price: 1875,
    mileageTier: '80k–115k miles',
    condition: 'good',
    warranty: '90 days',
    location: 'Denver, CO',
    image: '/images/used-engines.jpg',
    rating: 4.7,
    reviews: 48,
    description: '5.3L LS V8 engine from Chevy Tahoe. Compression within spec, no smoke, all accessories included.',
    compatibility: ['2007-2013 Chevrolet Tahoe / GMC Yukon 5.3L'],
    sku: 'ENG-53VNO',
    vinMatch: true,
  },
  {
    id: 'part-010',
    name: 'Engine 3.0L V6 Diesel',
    make: 'BMW 3 Series',
    partType: 'Engines',
    price: 2200,
    mileageTier: '65k–90k miles',
    condition: 'excellent',
    warranty: '90 days',
    location: 'Seattle, WA',
    image: '/images/used-engines.jpg',
    rating: 4.8,
    reviews: 36,
    description: 'BMW N55/B58 3.0L inline-6 engine from E90/F30. Service history available, turbo intact, no leaks.',
    compatibility: ['2008-2016 BMW 3 Series 3.0L'],
    sku: 'ENG-BMW30L',
    vinMatch: true,
  },
  {
    id: 'part-011',
    name: 'Alternator OEM Tested',
    make: 'Toyota Camry',
    partType: 'Parts',
    price: 185,
    condition: 'excellent',
    warranty: '90 days',
    location: 'Portland, OR',
    image: '/images/used-engines.jpg',
    rating: 4.8,
    reviews: 29,
    description: 'OEM Toyota Camry alternator, tested and clean. Core policy simple and fair. Verified output.',
    compatibility: ['2012-2017 Toyota Camry 2.5L'],
    sku: 'ALT-TC1217',
    vinMatch: false,
  },
  {
    id: 'part-012',
    name: 'Headlight Assembly OEM LH',
    make: 'Hyundai Tucson',
    partType: 'Parts',
    price: 230,
    condition: 'excellent',
    warranty: '60 days',
    location: 'Nashville, TN',
    image: '/images/used-engines.jpg',
    rating: 4.6,
    reviews: 21,
    description: 'OEM left headlight assembly from low-mileage Hyundai Tucson. Clear lens, no cracks or moisture.',
    compatibility: ['2016-2018 Hyundai Tucson'],
    sku: 'LGT-HYT16',
    vinMatch: false,
  },
]

export const partTypes = ['Engines', 'Transmissions', 'Parts']
export const conditions = ['excellent', 'good', 'fair']
export const warranties = ['60 days', '90 days', '30 days']
export const locations = [
  'Los Angeles, CA',
  'Houston, TX',
  'Phoenix, AZ',
  'Miami, FL',
  'Seattle, WA',
  'Dallas, TX',
  'Denver, CO',
  'Atlanta, GA',
  'Chicago, IL',
  'Detroit, MI',
  'Portland, OR',
  'Nashville, TN',
]
